###
POST {{baseUrl}}/load-fund-data
Content-Type: application/json

{
  "id": "15887",
  "customer_id": "528",
  "load_amount": "$3318.47",
  "time": "2000-01-01T00:00:00Z"
}

> {%
 client.test("Request executed successfully", function () {
   client.assert(response.status === 200, "Response status is not 200");
 });
%}
