funding:

  schemas:
    LoadFunds: "schemas/loadFundsSchema.json"

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3312}/${MYSQL_DATABASE:funding}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER:velocity_user}
    password: ${MYSQL_PASSWORD:velocity_pass}

  flyway:
    enabled: true
    user: ${MYSQL_USER:velocity_user}
    password: ${MYSQL_PASSWORD:velocity_pass}
    locations: 'classpath:db/migration'
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false


# Optional logging
logging:
  config: classpath:logback-dev.xml
  level:
    org.flywaydb: INFO
